language: node_js
install:
  - npm install
script:
  - set -e
  - npm run test:unit
  - npm run build
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
